export const dummyRegistrations = [
  {
    id: 1,
    fullName: "John Doe",
    contactNumber: 1234567890,
    email: "john.doe@example.com",
    canadianCitizen: "Yes",
    licenseType: "G",
    visaType: "PR",
    startDate: new Date("2025-05-01"),
    availability: {
      monday: true,
      tuesday: true,
      wednesday: true,
      thursday: true,
      friday: true,
      saturday: true,
      sunday: true,
    },
  },
  {
    id: 2,
    fullName: "Jane Smith",
    contactNumber: 1234567891,
    email: "jane.smith@example.com",
    canadianCitizen: "No",
    licenseType: "G2",
    visaType: "Work Permit",
    startDate: new Date("2025-05-02"),
    availability: {
      monday: false,
      tuesday: true,
      wednesday: true,
      thursday: false,
      friday: true,
      saturday: false,
      sunday: true,
    },
  },
  {
    id: 3,
    fullName: "Alice Johnson",
    contactNumber: 1234567892,
    email: "alice.johnson@example.com",
    canadianCitizen: "Yes",
    licenseType: "None",
    visaType: "Student Visa",
    startDate: new Date("2025-05-03"),
    availability: {
      monday: true,
      tuesday: false,
      wednesday: true,
      thursday: true,
      friday: false,
      saturday: false,
      sunday: true,
    },
  },
  {
    id: 4,
    fullName: "Bob Lee",
    contactNumber: 1234567893,
    email: "bob.lee@example.com",
    canadianCitizen: "No",
    licenseType: "G",
    visaType: "PR",
    startDate: new Date("2025-05-04"),
    availability: {
      monday: true,
      tuesday: true,
      wednesday: false,
      thursday: true,
      friday: true,
      saturday: true,
      sunday: false,
    },
  },
  {
    id: 5,
    fullName: "Charlie Kim",
    contactNumber: 1234567894,
    email: "charlie.kim@example.com",
    canadianCitizen: "Yes",
    licenseType: "G2",
    visaType: "Work Permit",
    startDate: new Date("2025-05-05"),
    availability: {
      monday: false,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: true,
      saturday: false,
      sunday: true,
    },
  },
  {
    id: 6,
    fullName: "Dana White",
    contactNumber: 1234567895,
    email: "dana.white@example.com",
    canadianCitizen: "No",
    licenseType: "None",
    visaType: "Student Visa",
    startDate: new Date("2025-05-06"),
    availability: {
      monday: true,
      tuesday: false,
      wednesday: true,
      thursday: true,
      friday: false,
      saturday: true,
      sunday: true,
    },
  },
  {
    id: 7,
    fullName: "Evan Turner",
    contactNumber: 1234567896,
    email: "evan.turner@example.com",
    canadianCitizen: "Yes",
    licenseType: "G",
    visaType: "Citizen",
    startDate: new Date("2025-05-07"),
    availability: {
      monday: true,
      tuesday: true,
      wednesday: false,
      thursday: true,
      friday: false,
      saturday: true,
      sunday: false,
    },
  },
  {
    id: 8,
    fullName: "Faith Morgan",
    contactNumber: 1234567897,
    email: "faith.morgan@example.com",
    canadianCitizen: "No",
    licenseType: "G2",
    visaType: "PR",
    startDate: new Date("2025-05-08"),
    availability: {
      monday: false,
      tuesday: true,
      wednesday: false,
      thursday: true,
      friday: true,
      saturday: true,
      sunday: true,
    },
  },
  {
    id: 9,
    fullName: "George Hill",
    contactNumber: 1234567898,
    email: "george.hill@example.com",
    canadianCitizen: "Yes",
    licenseType: "None",
    visaType: "Work Permit",
    startDate: new Date("2025-05-09"),
    availability: {
      monday: true,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: true,
      saturday: false,
      sunday: false,
    },
  },
  {
    id: 10,
    fullName: "Hannah Lee",
    contactNumber: 1234567899,
    email: "hannah.lee@example.com",
    canadianCitizen: "No",
    licenseType: "G",
    visaType: "Student Visa",
    startDate: new Date("2025-05-10"),
    availability: {
      monday: false,
      tuesday: true,
      wednesday: true,
      thursday: true,
      friday: true,
      saturday: false,
      sunday: true,
    },
  },
  {
    id: 11,
    fullName: "Isaac Newton",
    contactNumber: 1234567800,
    email: "isaac.newton@example.com",
    canadianCitizen: "Yes",
    licenseType: "G",
    visaType: "Citizen",
    startDate: new Date("2025-05-11"),
    availability: {
      monday: true,
      tuesday: false,
      wednesday: false,
      thursday: false,
      friday: true,
      saturday: true,
      sunday: false,
    },
  },
  {
    id: 12,
    fullName: "Julia Roberts",
    contactNumber: 1234567801,
    email: "julia.roberts@example.com",
    canadianCitizen: "No",
    licenseType: "G2",
    visaType: "PR",
    startDate: new Date("2025-05-12"),
    availability: {
      monday: true,
      tuesday: true,
      wednesday: true,
      thursday: false,
      friday: false,
      saturday: true,
      sunday: false,
    },
  },
  {
    id: 13,
    fullName: "Kevin Hart",
    contactNumber: 1234567802,
    email: "kevin.hart@example.com",
    canadianCitizen: "Yes",
    licenseType: "None",
    visaType: "Work Permit",
    startDate: new Date("2025-05-13"),
    availability: {
      monday: false,
      tuesday: false,
      wednesday: true,
      thursday: true,
      friday: true,
      saturday: false,
      sunday: true,
    },
  },
  {
    id: 14,
    fullName: "Laura Palmer",
    contactNumber: 1234567803,
    email: "laura.palmer@example.com",
    canadianCitizen: "No",
    licenseType: "G",
    visaType: "Student Visa",
    startDate: new Date("2025-05-14"),
    availability: {
      monday: true,
      tuesday: true,
      wednesday: false,
      thursday: false,
      friday: true,
      saturday: true,
      sunday: true,
    },
  },
  {
    id: 15,
    fullName: "Mike Ross",
    contactNumber: 1234567804,
    email: "mike.ross@example.com",
    canadianCitizen: "Yes",
    licenseType: "G2",
    visaType: "PR",
    startDate: new Date("2025-05-15"),
    availability: {
      monday: false,
      tuesday: true,
      wednesday: true,
      thursday: true,
      friday: false,
      saturday: true,
      sunday: false,
    },
  },
  {
    id: 16,
    fullName: "Nina Brown",
    contactNumber: 1234567805,
    email: "nina.brown@example.com",
    canadianCitizen: "No",
    licenseType: "None",
    visaType: "Citizen",
    startDate: new Date("2025-05-16"),
    availability: {
      monday: true,
      tuesday: false,
      wednesday: false,
      thursday: true,
      friday: true,
      saturday: true,
      sunday: true,
    },
  },
  {
    id: 17,
    fullName: "Oliver Stone",
    contactNumber: 1234567806,
    email: "oliver.stone@example.com",
    canadianCitizen: "Yes",
    licenseType: "G",
    visaType: "Work Permit",
    startDate: new Date("2025-05-17"),
    availability: {
      monday: false,
      tuesday: false,
      wednesday: true,
      thursday: true,
      friday: false,
      saturday: false,
      sunday: true,
    },
  },
  {
    id: 18,
    fullName: "Paula Abdul",
    contactNumber: 1234567807,
    email: "paula.abdul@example.com",
    canadianCitizen: "No",
    licenseType: "G2",
    visaType: "Student Visa",
    startDate: new Date("2025-05-18"),
    availability: {
      monday: true,
      tuesday: true,
      wednesday: true,
      thursday: false,
      friday: true,
      saturday: true,
      sunday: false,
    },
  },
  {
    id: 19,
    fullName: "Quincy Adams",
    contactNumber: 1234567808,
    email: "quincy.adams@example.com",
    canadianCitizen: "Yes",
    licenseType: "None",
    visaType: "Citizen",
    startDate: new Date("2025-05-19"),
    availability: {
      monday: false,
      tuesday: true,
      wednesday: false,
      thursday: true,
      friday: true,
      saturday: false,
      sunday: true,
    },
  },
  {
    id: 20,
    fullName: "Rachel Green",
    contactNumber: 1234567809,
    email: "rachel.green@example.com",
    canadianCitizen: "No",
    licenseType: "G",
    visaType: "PR",
    startDate: new Date("2025-05-20"),
    availability: {
      monday: true,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: true,
      saturday: true,
      sunday: false,
    },
  },
];

export const dummyQuoteRequests = [
  {
    id: 1,
    firstName: "Alice",
    lastName: "Wong",
    email: "alice.wong@example.com",
    contact_reason: "Partnership inquiry",
    delivery_reason: "Need regular weekly deliveries",
    shipping_volume: "Medium",
    contact_number: 1234567890,
    help: "I'd like to understand your delivery process better.",
  },
  {
    id: 2,
    firstName: "Bob",
    lastName: "Johnson",
    email: "bob.johnson@example.com",
    contact_reason: "Quote request",
    delivery_reason: "Launching new branch",
    shipping_volume: "High",
    contact_number: 1234567891,
    help: "Need pricing details and options.",
  },
  {
    id: 3,
    firstName: "Carol",
    lastName: "Martinez",
    email: "carol.martinez@example.com",
    contact_reason: "Service issue",
    delivery_reason: "Missed delivery",
    shipping_volume: "Low",
    contact_number: 1234567892,
    help: "Our package was not delivered. Please assist.",
  },
  {
    id: 4,
    firstName: "David",
    lastName: "Lee",
    email: "david.lee@example.com",
    contact_reason: "General inquiry",
    delivery_reason: "Upcoming event",
    shipping_volume: "Medium",
    contact_number: 1234567893,
    help: "Do you offer event-specific shipping?",
  },
  {
    id: 5,
    firstName: "Eva",
    lastName: "Green",
    email: "eva.green@example.com",
    contact_reason: "Job application",
    delivery_reason: "N/A",
    shipping_volume: "None",
    contact_number: 1234567894,
    help: "I'm interested in working with your logistics team.",
  },
  {
    id: 6,
    firstName: "Frank",
    lastName: "Nguyen",
    email: "frank.nguyen@example.com",
    contact_reason: "Follow-up",
    delivery_reason: "Previous quote",
    shipping_volume: "High",
    contact_number: 1234567895,
    help: "We’d like to move forward with your quote.",
  },
  {
    id: 7,
    firstName: "Grace",
    lastName: "Turner",
    email: "grace.turner@example.com",
    contact_reason: "Complaint",
    delivery_reason: "Damaged goods",
    shipping_volume: "Low",
    contact_number: 1234567896,
    help: "The shipment arrived broken.",
  },
  {
    id: 8,
    firstName: "Henry",
    lastName: "Adams",
    email: "henry.adams@example.com",
    contact_reason: "Billing question",
    delivery_reason: "Invoice error",
    shipping_volume: "Medium",
    contact_number: 1234567897,
    help: "Please correct the overcharge on our bill.",
  },
  {
    id: 9,
    firstName: "Isla",
    lastName: "Rodriguez",
    email: "isla.rodriguez@example.com",
    contact_reason: "Request demo",
    delivery_reason: "Exploring providers",
    shipping_volume: "High",
    contact_number: 1234567898,
    help: "Can you show us a demo of your system?",
  },
  {
    id: 10,
    firstName: "Jack",
    lastName: "Chen",
    email: "jack.chen@example.com",
    contact_reason: "Technical issue",
    delivery_reason: "Tracking problem",
    shipping_volume: "Medium",
    contact_number: 1234567899,
    help: "Tracking link not updating.",
  },
  {
    id: 11,
    firstName: "Kara",
    lastName: "Bell",
    email: "kara.bell@example.com",
    contact_reason: "Reschedule",
    delivery_reason: "Not available",
    shipping_volume: "Low",
    contact_number: 1234567800,
    help: "Please reschedule for tomorrow.",
  },
  {
    id: 12,
    firstName: "Leo",
    lastName: "Sanders",
    email: "leo.sanders@example.com",
    contact_reason: "Feedback",
    delivery_reason: "Great service",
    shipping_volume: "Low",
    contact_number: 1234567801,
    help: "We’re really happy with your team!",
  },
  {
    id: 13,
    firstName: "Maya",
    lastName: "Fox",
    email: "maya.fox@example.com",
    contact_reason: "Product return",
    delivery_reason: "Wrong item",
    shipping_volume: "None",
    contact_number: 1234567802,
    help: "How can I return this product?",
  },
  {
    id: 14,
    firstName: "Nathan",
    lastName: "Clark",
    email: "nathan.clark@example.com",
    contact_reason: "Urgent delivery",
    delivery_reason: "Last-minute request",
    shipping_volume: "High",
    contact_number: 1234567803,
    help: "Can you deliver by tonight?",
  },
  {
    id: 15,
    firstName: "Olivia",
    lastName: "King",
    email: "olivia.king@example.com",
    contact_reason: "Partnership proposal",
    delivery_reason: "Shared logistics",
    shipping_volume: "Medium",
    contact_number: 1234567804,
    help: "Looking to partner with your team.",
  },
  {
    id: 16,
    firstName: "Paul",
    lastName: "Stone",
    email: "paul.stone@example.com",
    contact_reason: "Driver issue",
    delivery_reason: "Unprofessional behavior",
    shipping_volume: "Low",
    contact_number: 1234567805,
    help: "Please address your driver’s conduct.",
  },
  {
    id: 17,
    firstName: "Quinn",
    lastName: "Banks",
    email: "quinn.banks@example.com",
    contact_reason: "Delivery confirmation",
    delivery_reason: "Late package",
    shipping_volume: "Low",
    contact_number: 1234567806,
    help: "Did the package arrive?",
  },
  {
    id: 18,
    firstName: "Rita",
    lastName: "Harper",
    email: "rita.harper@example.com",
    contact_reason: "Inquiry",
    delivery_reason: "International shipping",
    shipping_volume: "High",
    contact_number: 1234567807,
    help: "Do you ship to the US?",
  },
  {
    id: 19,
    firstName: "Sam",
    lastName: "Porter",
    email: "sam.porter@example.com",
    contact_reason: "Lost item",
    delivery_reason: "Tracking lost",
    shipping_volume: "Low",
    contact_number: 1234567808,
    help: "My item disappeared from tracking.",
  },
  {
    id: 20,
    firstName: "Tina",
    lastName: "Baker",
    email: "tina.baker@example.com",
    contact_reason: "Schedule pickup",
    delivery_reason: "Bulk shipping",
    shipping_volume: "High",
    contact_number: 1234567809,
    help: "Need to schedule a warehouse pickup.",
  },
];

export const dummySupportRequests = [
  {
    id: 1,
    contact_reason: "Package not delivered",
    details: "The package was marked as delivered but never received.",
    firstName: "Alice",
    lastName: "Taylor",
    email: "alice.taylor@example.com",
    tracking_number: "TRK12345",
    country: "Canada",
    province: "Ontario",
    location: "GTA",
    issue: "Missing delivery",
  },
  {
    id: 2,
    contact_reason: "Damaged product",
    details: "The box was crushed and item inside is broken.",
    firstName: "Brian",
    lastName: "Miller",
    email: "brian.miller@example.com",
    tracking_number: "TRK54321",
    country: "Canada",
    province: "Ontario",
    location: "Whitby",
    issue: "Item damaged in transit",
  },
  {
    id: 3,
    contact_reason: "Wrong address",
    details: "Tracking shows delivery in a different city.",
    firstName: "Cathy",
    lastName: "Singh",
    email: "cathy.singh@example.com",
    tracking_number: "TRK67890",
    country: "Canada",
    province: "Ontario",
    location: "Windsor",
    issue: "Incorrect delivery address",
  },
  {
    id: 4,
    contact_reason: "Late delivery",
    details: "Expected delivery last week, still not here.",
    firstName: "Daniel",
    lastName: "Nguyen",
    email: "daniel.nguyen@example.com",
    tracking_number: "TRK11223",
    country: "Canada",
    province: "Ontario",
    location: "GTA",
    issue: "Delivery delay",
  },
  {
    id: 5,
    contact_reason: "No updates",
    details: "Tracking hasn’t changed in 5 days.",
    firstName: "Eva",
    lastName: "Chen",
    email: "eva.chen@example.com",
    tracking_number: "TRK33445",
    country: "Canada",
    province: "Ontario",
    location: "Whitby",
    issue: "Stalled tracking info",
  },
  {
    id: 6,
    contact_reason: "Delivery reschedule",
    details: "Need to change delivery date.",
    firstName: "Frank",
    lastName: "Lam",
    email: "frank.lam@example.com",
    tracking_number: "TRK55667",
    country: "Canada",
    province: "Ontario",
    location: "Windsor",
    issue: "Reschedule request",
  },
  {
    id: 7,
    contact_reason: "Wrong item",
    details: "Received wrong product SKU.",
    firstName: "Grace",
    lastName: "Robinson",
    email: "grace.robinson@example.com",
    tracking_number: "TRK77889",
    country: "Canada",
    province: "Ontario",
    location: "GTA",
    issue: "Incorrect product",
  },
  {
    id: 8,
    contact_reason: "Lost package",
    details: "Carrier can't locate the shipment.",
    firstName: "Henry",
    lastName: "Kaur",
    email: "henry.kaur@example.com",
    tracking_number: "TRK99001",
    country: "Canada",
    province: "Ontario",
    location: "Whitby",
    issue: "Package lost",
  },
  {
    id: 9,
    contact_reason: "Damaged label",
    details: "Label was unreadable, return to sender.",
    firstName: "Ivy",
    lastName: "Smith",
    email: "ivy.smith@example.com",
    tracking_number: "TRK21314",
    country: "Canada",
    province: "Ontario",
    location: "Windsor",
    issue: "Unreadable tracking label",
  },
  {
    id: 10,
    contact_reason: "Wrong province",
    details: "Package routed to wrong province.",
    firstName: "Jack",
    lastName: "Ali",
    email: "jack.ali@example.com",
    tracking_number: "TRK15161",
    country: "Canada",
    province: "Ontario",
    location: "GTA",
    issue: "Misrouted delivery",
  },
  {
    id: 11,
    contact_reason: "Held at facility",
    details: "Stuck at Mississauga depot.",
    firstName: "Kate",
    lastName: "Brown",
    email: "kate.brown@example.com",
    tracking_number: "TRK17181",
    country: "Canada",
    province: "Ontario",
    location: "Whitby",
    issue: "Facility hold",
  },
  {
    id: 12,
    contact_reason: "Return request",
    details: "I want to return the item.",
    firstName: "Leo",
    lastName: "Singh",
    email: "leo.singh@example.com",
    tracking_number: "TRK19202",
    country: "Canada",
    province: "Ontario",
    location: "Windsor",
    issue: "Return initiation",
  },
  {
    id: 13,
    contact_reason: "Incomplete delivery",
    details: "Missing parts in the box.",
    firstName: "Mona",
    lastName: "Clark",
    email: "mona.clark@example.com",
    tracking_number: "TRK20212",
    country: "Canada",
    province: "Ontario",
    location: "GTA",
    issue: "Partial shipment",
  },
  {
    id: 14,
    contact_reason: "Wrong tracking number",
    details: "Number doesn't match my order.",
    firstName: "Noah",
    lastName: "Lee",
    email: "noah.lee@example.com",
    tracking_number: "TRK22223",
    country: "Canada",
    province: "Ontario",
    location: "Whitby",
    issue: "Invalid tracking info",
  },
  {
    id: 15,
    contact_reason: "Contact driver",
    details: "Can the driver call on arrival?",
    firstName: "Olivia",
    lastName: "Green",
    email: "olivia.green@example.com",
    tracking_number: "TRK24242",
    country: "Canada",
    province: "Ontario",
    location: "Windsor",
    issue: "Driver communication request",
  },
  {
    id: 16,
    contact_reason: "Delay explanation",
    details: "Why is my package still in transit?",
    firstName: "Peter",
    lastName: "Martin",
    email: "peter.martin@example.com",
    tracking_number: "TRK26262",
    country: "Canada",
    province: "Ontario",
    location: "GTA",
    issue: "Long transit delay",
  },
  {
    id: 17,
    contact_reason: "Re-attempt delivery",
    details: "I missed the first delivery.",
    firstName: "Queenie",
    lastName: "Patel",
    email: "queenie.patel@example.com",
    tracking_number: "TRK28282",
    country: "Canada",
    province: "Ontario",
    location: "Whitby",
    issue: "Missed delivery attempt",
  },
  {
    id: 18,
    contact_reason: "Billing discrepancy",
    details: "Charged for express but delivered ground.",
    firstName: "Raj",
    lastName: "Thompson",
    email: "raj.thompson@example.com",
    tracking_number: "TRK30303",
    country: "Canada",
    province: "Ontario",
    location: "Windsor",
    issue: "Incorrect billing type",
  },
  {
    id: 19,
    contact_reason: "Update address",
    details: "I moved, update delivery location.",
    firstName: "Sophie",
    lastName: "White",
    email: "sophie.white@example.com",
    tracking_number: "TRK32323",
    country: "Canada",
    province: "Ontario",
    location: "GTA",
    issue: "Change address",
  },
  {
    id: 20,
    contact_reason: "Lost label",
    details: "The return label is missing.",
    firstName: "Tom",
    lastName: "Walker",
    email: "tom.walker@example.com",
    tracking_number: "TRK34343",
    country: "Canada",
    province: "Ontario",
    location: "Whitby",
    issue: "Missing return label",
  },
];
