export const dummyRegistrations = [
  {
    id: 1,
    fullName: "John Doe",
    contactNumber: 1234567890,
    email: "john.doe@example.com",
    canadianCitizen: "Yes",
    licenseType: "G",
    visaType: "PR",
    startDate: new Date("2025-05-01"),
    availability: {
      monday: true,
      tuesday: true,
      wednesday: true,
      thursday: true,
      friday: true,
      saturday: true,
      sunday: true,
    },
  },
  {
    id: 2,
    fullName: "Jane Smith",
    contactNumber: 1234567891,
    email: "jane.smith@example.com",
    canadianCitizen: "No",
    licenseType: "G2",
    visaType: "Work Permit",
    startDate: new Date("2025-05-02"),
    availability: {
      monday: false,
      tuesday: true,
      wednesday: true,
      thursday: false,
      friday: true,
      saturday: false,
      sunday: true,
    },
  },
  {
    id: 3,
    fullName: "Alice Johnson",
    contactNumber: 1234567892,
    email: "alice.johnson@example.com",
    canadianCitizen: "Yes",
    licenseType: "None",
    visaType: "Student Visa",
    startDate: new Date("2025-05-03"),
    availability: {
      monday: true,
      tuesday: false,
      wednesday: true,
      thursday: true,
      friday: false,
      saturday: false,
      sunday: true,
    },
  },
  {
    id: 4,
    fullName: "Bob Lee",
    contactNumber: 1234567893,
    email: "bob.lee@example.com",
    canadianCitizen: "No",
    licenseType: "G",
    visaType: "PR",
    startDate: new Date("2025-05-04"),
    availability: {
      monday: true,
      tuesday: true,
      wednesday: false,
      thursday: true,
      friday: true,
      saturday: true,
      sunday: false,
    },
  },
  {
    id: 5,
    fullName: "Charlie Kim",
    contactNumber: 1234567894,
    email: "charlie.kim@example.com",
    canadianCitizen: "Yes",
    licenseType: "G2",
    visaType: "Work Permit",
    startDate: new Date("2025-05-05"),
    availability: {
      monday: false,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: true,
      saturday: false,
      sunday: true,
    },
  },
  {
    id: 6,
    fullName: "Dana White",
    contactNumber: 1234567895,
    email: "dana.white@example.com",
    canadianCitizen: "No",
    licenseType: "None",
    visaType: "Student Visa",
    startDate: new Date("2025-05-06"),
    availability: {
      monday: true,
      tuesday: false,
      wednesday: true,
      thursday: true,
      friday: false,
      saturday: true,
      sunday: true,
    },
  },
  {
    id: 7,
    fullName: "Evan Turner",
    contactNumber: 1234567896,
    email: "evan.turner@example.com",
    canadianCitizen: "Yes",
    licenseType: "G",
    visaType: "Citizen",
    startDate: new Date("2025-05-07"),
    availability: {
      monday: true,
      tuesday: true,
      wednesday: false,
      thursday: true,
      friday: false,
      saturday: true,
      sunday: false,
    },
  },
  {
    id: 8,
    fullName: "Faith Morgan",
    contactNumber: 1234567897,
    email: "faith.morgan@example.com",
    canadianCitizen: "No",
    licenseType: "G2",
    visaType: "PR",
    startDate: new Date("2025-05-08"),
    availability: {
      monday: false,
      tuesday: true,
      wednesday: false,
      thursday: true,
      friday: true,
      saturday: true,
      sunday: true,
    },
  },
  {
    id: 9,
    fullName: "George Hill",
    contactNumber: 1234567898,
    email: "george.hill@example.com",
    canadianCitizen: "Yes",
    licenseType: "None",
    visaType: "Work Permit",
    startDate: new Date("2025-05-09"),
    availability: {
      monday: true,
      tuesday: false,
      wednesday: true,
      thursday: false,
      friday: true,
      saturday: false,
      sunday: false,
    },
  },
];

export const dummyQuoteRequests = [
  {
    id: 1,
    firstName: "Alice",
    lastName: "Wong",
    email: "alice.wong@example.com",
    contact_reason: "Partnership inquiry",
    delivery_reason: "Need regular weekly deliveries",
    shipping_volume: "Medium",
    contact_number: 1234567890,
    help: "I'd like to understand your delivery process better.",
  },
  {
    id: 2,
    firstName: "Bob",
    lastName: "Johnson",
    email: "bob.johnson@example.com",
    contact_reason: "Quote request",
    delivery_reason: "Launching new branch",
    shipping_volume: "High",
    contact_number: 1234567891,
    help: "Need pricing details and options.",
  },
  {
    id: 3,
    firstName: "Carol",
    lastName: "Martinez",
    email: "carol.martinez@example.com",
    contact_reason: "Service issue",
    delivery_reason: "Missed delivery",
    shipping_volume: "Low",
    contact_number: 1234567892,
    help: "Our package was not delivered. Please assist.",
  },
  {
    id: 4,
    firstName: "David",
    lastName: "Lee",
    email: "david.lee@example.com",
    contact_reason: "General inquiry",
    delivery_reason: "Upcoming event",
    shipping_volume: "Medium",
    contact_number: 1234567893,
    help: "Do you offer event-specific shipping?",
  },
  {
    id: 5,
    firstName: "Eva",
    lastName: "Green",
    email: "eva.green@example.com",
    contact_reason: "Job application",
    delivery_reason: "N/A",
    shipping_volume: "None",
    contact_number: 1234567894,
    help: "I'm interested in working with your logistics team.",
  },
  {
    id: 6,
    firstName: "Frank",
    lastName: "Nguyen",
    email: "frank.nguyen@example.com",
    contact_reason: "Follow-up",
    delivery_reason: "Previous quote",
    shipping_volume: "High",
    contact_number: 1234567895,
    help: "We’d like to move forward with your quote.",
  },
  {
    id: 7,
    firstName: "Grace",
    lastName: "Turner",
    email: "grace.turner@example.com",
    contact_reason: "Complaint",
    delivery_reason: "Damaged goods",
    shipping_volume: "Low",
    contact_number: 1234567896,
    help: "The shipment arrived broken.",
  },
  {
    id: 8,
    firstName: "Henry",
    lastName: "Adams",
    email: "henry.adams@example.com",
    contact_reason: "Billing question",
    delivery_reason: "Invoice error",
    shipping_volume: "Medium",
    contact_number: 1234567897,
    help: "Please correct the overcharge on our bill.",
  },
  {
    id: 9,
    firstName: "Isla",
    lastName: "Rodriguez",
    email: "isla.rodriguez@example.com",
    contact_reason: "Request demo",
    delivery_reason: "Exploring providers",
    shipping_volume: "High",
    contact_number: 1234567898,
    help: "Can you show us a demo of your system?",
  },
  {
    id: 10,
    firstName: "Jack",
    lastName: "Chen",
    email: "jack.chen@example.com",
    contact_reason: "Technical issue",
    delivery_reason: "Tracking problem",
    shipping_volume: "Medium",
    contact_number: 1234567899,
    help: "Tracking link not updating.",
  },
];

export const dummySupportRequests = [
  {
    id: 1,
    contact_reason: "Package not delivered",
    details: "The package was marked as delivered but never received.",
    firstName: "Alice",
    lastName: "Taylor",
    email: "alice.taylor@example.com",
    tracking_number: "TRK12345",
    country: "Canada",
    province: "Ontario",
    location: "GTA",
    issue: "Missing delivery",
  },
  {
    id: 2,
    contact_reason: "Damaged product",
    details: "The box was crushed and item inside is broken.",
    firstName: "Brian",
    lastName: "Miller",
    email: "brian.miller@example.com",
    tracking_number: "TRK54321",
    country: "Canada",
    province: "Ontario",
    location: "Whitby",
    issue: "Item damaged in transit",
  },
  {
    id: 3,
    contact_reason: "Wrong address",
    details: "Tracking shows delivery in a different city.",
    firstName: "Cathy",
    lastName: "Singh",
    email: "cathy.singh@example.com",
    tracking_number: "TRK67890",
    country: "Canada",
    province: "Ontario",
    location: "Windsor",
    issue: "Incorrect delivery address",
  },
  {
    id: 4,
    contact_reason: "Late delivery",
    details: "Expected delivery last week, still not here.",
    firstName: "Daniel",
    lastName: "Nguyen",
    email: "daniel.nguyen@example.com",
    tracking_number: "TRK11223",
    country: "Canada",
    province: "Ontario",
    location: "GTA",
    issue: "Delivery delay",
  },
  {
    id: 5,
    contact_reason: "No updates",
    details: "Tracking hasn’t changed in 5 days.",
    firstName: "Eva",
    lastName: "Chen",
    email: "eva.chen@example.com",
    tracking_number: "TRK33445",
    country: "Canada",
    province: "Ontario",
    location: "Whitby",
    issue: "Stalled tracking info",
  },
  {
    id: 6,
    contact_reason: "Delivery reschedule",
    details: "Need to change delivery date.",
    firstName: "Frank",
    lastName: "Lam",
    email: "frank.lam@example.com",
    tracking_number: "TRK55667",
    country: "Canada",
    province: "Ontario",
    location: "Windsor",
    issue: "Reschedule request",
  },
  {
    id: 7,
    contact_reason: "Wrong item",
    details: "Received wrong product SKU.",
    firstName: "Grace",
    lastName: "Robinson",
    email: "grace.robinson@example.com",
    tracking_number: "TRK77889",
    country: "Canada",
    province: "Ontario",
    location: "GTA",
    issue: "Incorrect product",
  },
  {
    id: 8,
    contact_reason: "Lost package",
    details: "Carrier can't locate the shipment.",
    firstName: "Henry",
    lastName: "Kaur",
    email: "henry.kaur@example.com",
    tracking_number: "TRK99001",
    country: "Canada",
    province: "Ontario",
    location: "Whitby",
    issue: "Package lost",
  },
  {
    id: 9,
    contact_reason: "Damaged label",
    details: "Label was unreadable, return to sender.",
    firstName: "Ivy",
    lastName: "Smith",
    email: "ivy.smith@example.com",
    tracking_number: "TRK21314",
    country: "Canada",
    province: "Ontario",
    location: "Windsor",
    issue: "Unreadable tracking label",
  },
  {
    id: 10,
    contact_reason: "Wrong province",
    details: "Package routed to wrong province.",
    firstName: "Jack",
    lastName: "Ali",
    email: "jack.ali@example.com",
    tracking_number: "TRK15161",
    country: "Canada",
    province: "Ontario",
    location: "GTA",
    issue: "Misrouted delivery",
  },
];
